#### This code is to test numpy array slicing as well as trying out machine learning stuff 

In [1]:
import numpy as np
import pandas as pd


In this part of the code, I will read a csv file containing some stuff.

In [2]:
dataset = pd.read_csv("BBCN.csv")

dataset.head(10)

MaritalStatus  Gender  YearlyIncome  TotalChildren  NumberChildrenAtHome  \
0              5       1           9.0              2                     0   
1              5       1           6.0              3                     3   
2              5       1           6.0              3                     3   
3              5       2           7.0              0                     0   
4              5       2           8.0              5                     5   
5              5       1           7.0              0                     0   
6              5       2           7.0              0                     0   
7              5       1           6.0              3                     3   
8              5       2           6.0              4                     4   
9              5       1           7.0              0                     0   

   EnglishEducation  HouseOwnerFlag  NumberCarsOwned  CommuteDistance  Region  \
0                 5               1                0                2       2   
1                 5               0                1                1       2   
2                 5               1                1                5       2   
3                 5               0                1               10       2   
4                 5               1                4                2       2   
5                 5               1                1               10       2   
6                 5               1                1               10       2   
7                 5               1                2                1       2   
8                 5               1                3               20       2   
9                 5               0                1               10       2   

   Age  BikeBuyer  
0    5          1  
1    4          1  
2    4          1  
3    5          1  
4    5          1  
5    4          1  
6    4          1  
7    4          1  
8    4          1  
9    4          1

#### Above, we have loaded the dataset and taken a sneak preview at what the dataset contains.
#### We have loaded the first 10 rows and columns of the dataset which we read from the csv file

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
row_a = a[1,:]
print(row_a)

[5 6 7 8]
